/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface HeaderLogo {
    }
    interface LandingSection {
    }
    interface PeopleHeader {
    }
    interface PeopleSection {
    }
    interface PersonalBio {
        "location": string;
        "name": string;
        "role": string;
    }
    interface TeamCarousel {
    }
    interface TeamHeader {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHeaderLogoElement extends Components.HeaderLogo, HTMLStencilElement {
    }
    var HTMLHeaderLogoElement: {
        prototype: HTMLHeaderLogoElement;
        new (): HTMLHeaderLogoElement;
    };
    interface HTMLLandingSectionElement extends Components.LandingSection, HTMLStencilElement {
    }
    var HTMLLandingSectionElement: {
        prototype: HTMLLandingSectionElement;
        new (): HTMLLandingSectionElement;
    };
    interface HTMLPeopleHeaderElement extends Components.PeopleHeader, HTMLStencilElement {
    }
    var HTMLPeopleHeaderElement: {
        prototype: HTMLPeopleHeaderElement;
        new (): HTMLPeopleHeaderElement;
    };
    interface HTMLPeopleSectionElement extends Components.PeopleSection, HTMLStencilElement {
    }
    var HTMLPeopleSectionElement: {
        prototype: HTMLPeopleSectionElement;
        new (): HTMLPeopleSectionElement;
    };
    interface HTMLPersonalBioElement extends Components.PersonalBio, HTMLStencilElement {
    }
    var HTMLPersonalBioElement: {
        prototype: HTMLPersonalBioElement;
        new (): HTMLPersonalBioElement;
    };
    interface HTMLTeamCarouselElement extends Components.TeamCarousel, HTMLStencilElement {
    }
    var HTMLTeamCarouselElement: {
        prototype: HTMLTeamCarouselElement;
        new (): HTMLTeamCarouselElement;
    };
    interface HTMLTeamHeaderElement extends Components.TeamHeader, HTMLStencilElement {
    }
    var HTMLTeamHeaderElement: {
        prototype: HTMLTeamHeaderElement;
        new (): HTMLTeamHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "header-logo": HTMLHeaderLogoElement;
        "landing-section": HTMLLandingSectionElement;
        "people-header": HTMLPeopleHeaderElement;
        "people-section": HTMLPeopleSectionElement;
        "personal-bio": HTMLPersonalBioElement;
        "team-carousel": HTMLTeamCarouselElement;
        "team-header": HTMLTeamHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface HeaderLogo {
    }
    interface LandingSection {
    }
    interface PeopleHeader {
    }
    interface PeopleSection {
    }
    interface PersonalBio {
        "location"?: string;
        "name"?: string;
        "role"?: string;
    }
    interface TeamCarousel {
    }
    interface TeamHeader {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "header-logo": HeaderLogo;
        "landing-section": LandingSection;
        "people-header": PeopleHeader;
        "people-section": PeopleSection;
        "personal-bio": PersonalBio;
        "team-carousel": TeamCarousel;
        "team-header": TeamHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "header-logo": LocalJSX.HeaderLogo & JSXBase.HTMLAttributes<HTMLHeaderLogoElement>;
            "landing-section": LocalJSX.LandingSection & JSXBase.HTMLAttributes<HTMLLandingSectionElement>;
            "people-header": LocalJSX.PeopleHeader & JSXBase.HTMLAttributes<HTMLPeopleHeaderElement>;
            "people-section": LocalJSX.PeopleSection & JSXBase.HTMLAttributes<HTMLPeopleSectionElement>;
            "personal-bio": LocalJSX.PersonalBio & JSXBase.HTMLAttributes<HTMLPersonalBioElement>;
            "team-carousel": LocalJSX.TeamCarousel & JSXBase.HTMLAttributes<HTMLTeamCarouselElement>;
            "team-header": LocalJSX.TeamHeader & JSXBase.HTMLAttributes<HTMLTeamHeaderElement>;
        }
    }
}
